"""usuarios, pedidos e items

Revision ID: 2636013e7bdf
Revises: 
Create Date: 2026-08-25 12:41:02.897599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2636013e7bdf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_id'), 'pedidos', ['id'], unique=False)
    op.create_table('items_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('precio_unitario', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_pedido_id'), 'items_pedido', ['id'], unique=False)
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_index(op.f('ix_categorias_nombre'), table_name='categorias')
    op.drop_table('categorias')
    op.add_column('productos', sa.Column('cuotas', sa.Integer(), nullable=True))
    op.add_column('productos', sa.Column('garantia', sa.String(), nullable=True))
    op.alter_column('productos', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('productos', 'precio_final',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('productos', 'stock',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_productos_nombre'), 'productos', ['nombre'], unique=False)
    op.drop_column('productos', 'garantia_meses')
    op.drop_column('productos', 'cuotas_valor')
    op.drop_column('productos', 'cuotas_cantidad')
    op.add_column('usuarios', sa.Column('password_hash', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('rol', sa.String(), nullable=True))
    op.drop_index(op.f('ix_usuarios_nombre'), table_name='usuarios')
    op.drop_column('usuarios', 'es_admin')
    op.drop_column('usuarios', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('usuarios', sa.Column('es_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_usuarios_nombre'), 'usuarios', ['nombre'], unique=True)
    op.drop_column('usuarios', 'rol')
    op.drop_column('usuarios', 'password_hash')
    op.add_column('productos', sa.Column('cuotas_cantidad', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('productos', sa.Column('cuotas_valor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('productos', sa.Column('garantia_meses', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_productos_nombre'), table_name='productos')
    op.alter_column('productos', 'stock',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('productos', 'precio_final',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('productos', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('productos', 'garantia')
    op.drop_column('productos', 'cuotas')
    op.create_table('categorias',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('categorias_pkey'))
    )
    op.create_index(op.f('ix_categorias_nombre'), 'categorias', ['nombre'], unique=True)
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    op.drop_index(op.f('ix_items_pedido_id'), table_name='items_pedido')
    op.drop_table('items_pedido')
    op.drop_index(op.f('ix_pedidos_id'), table_name='pedidos')
    op.drop_table('pedidos')
    # ### end Alembic commands ###
