"""usuarios con auth

Revision ID: 36dab8c3a1ad
Revises: 3a6dd89d1fda
Create Date: 2026-09-07 09:41:39.018949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36dab8c3a1ad'
down_revision: Union[str, Sequence[str], None] = '3a6dd89d1fda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Borrar primero la tabla hija (items_pedido) para liberar la Foreign Key
    op.drop_index(op.f('ix_items_pedido_id'), table_name='items_pedido')
    op.drop_table('items_pedido')

    # 2. Borrar la tabla padre (pedidos)
    op.drop_index(op.f('ix_pedidos_id'), table_name='pedidos')
    op.drop_table('pedidos')

    # 3. Actualizar productos
    op.alter_column('productos', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('productos', 'precio_final',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('productos', 'stock',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_productos_nombre'), table_name='productos')

    # 4. Agregar columnas nuevas a usuarios con valores temporales para registros existentes
    op.add_column('usuarios', sa.Column('hashed_password', sa.String(), nullable=False, server_default='CHANGE_ME'))
    op.add_column('usuarios', sa.Column('acepto_tratamiento', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('usuarios', sa.Column('fecha_consentimiento', sa.DateTime(timezone=True), nullable=True))
    
    # Remover los defaults del DDL para futuros inserts
    op.alter_column('usuarios', 'hashed_password', server_default=None)
    op.alter_column('usuarios', 'acepto_tratamiento', server_default=None)

    # 5. Sanitizar datos existentes en usuarios antes de aplicar NOT NULL
    op.execute("UPDATE usuarios SET rol = 'cliente' WHERE rol IS NULL")
    op.execute("UPDATE usuarios SET nombre = 'Usuario' WHERE nombre IS NULL")
    op.execute("UPDATE usuarios SET email = 'sin_email@domain.com' WHERE email IS NULL")

    # 6. Alterar restricciones NOT NULL en usuarios
    op.alter_column('usuarios', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usuarios', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usuarios', 'rol',
               existing_type=sa.VARCHAR(),
               nullable=False)
    
    # 7. Eliminar columna password_hash si existe
    op.drop_column('usuarios', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('usuarios', 'rol',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usuarios', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usuarios', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('usuarios', 'fecha_consentimiento')
    op.drop_column('usuarios', 'acepto_tratamiento')
    op.drop_column('usuarios', 'hashed_password')
    op.create_index(op.f('ix_productos_nombre'), 'productos', ['nombre'], unique=False)
    op.alter_column('productos', 'stock',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('productos', 'precio_final',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('productos', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('items_pedido',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pedido_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('producto_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('precio_unitario', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], name=op.f('items_pedido_pedido_id_fkey')),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name=op.f('items_pedido_producto_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('items_pedido_pkey'))
    )
    op.create_index(op.f('ix_items_pedido_id'), 'items_pedido', ['id'], unique=False)
    op.create_table('pedidos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('pedidos_usuario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pedidos_pkey'))
    )
    op.create_index(op.f('ix_pedidos_id'), 'pedidos', ['id'], unique=False)
    # ### end Alembic commands ###